# What I want to do here, is practice with real data from the 2022 Stack Overflow survey, to get some insights.

1. First of all, I just want to get just an overview about the data I wanna work with

In [149]:
import pandas as pd
import numpy as np
original_df = pd.read_csv('/Users/daniboy/Desktop/Youtube_Courses/Pandas_Corey_Schafer/stack-overflow-developer-survey-2022/survey_results_public.csv')
df_schema = pd.read_csv('/Users/daniboy/Desktop/Youtube_Courses/Pandas_Corey_Schafer/stack-overflow-developer-survey-2022/survey_results_schema.csv')
pd.set_option('display.max_columns',85)
pd.set_option('display.max_rows',85)

In [150]:
original_df.head()

,ResponseId,MainBranch,Employment,RemoteWork,CodingActivities,EdLevel,LearnCode,LearnCodeOnline,LearnCodeCoursesCert,YearsCode,YearsCodePro,DevType,OrgSize,PurchaseInfluence,BuyNewTool,Country,Currency,CompTotal,CompFreq,LanguageHaveWorkedWith,LanguageWantToWorkWith,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,PlatformHaveWorkedWith,PlatformWantToWorkWith,WebframeHaveWorkedWith,WebframeWantToWorkWith,MiscTechHaveWorkedWith,MiscTechWantToWorkWith,ToolsTechHaveWorkedWith,ToolsTechWantToWorkWith,NEWCollabToolsHaveWorkedWith,NEWCollabToolsWantToWorkWith,OpSysProfessional use,OpSysPersonal use,VersionControlSystem,VCInteraction,VCHostingPersonal use,VCHostingProfessional use,OfficeStackAsyncHaveWorkedWith,OfficeStackAsyncWantToWorkWith,OfficeStackSyncHaveWorkedWith,OfficeStackSyncWantToWorkWith,Blockchain,NEWSOSites,SOVisitFreq,SOAccount,SOPartFreq,SOComm,Age,Gender,Trans,Sexuality,Ethnicity,Accessibility,MentalHealth,TBranch,ICorPM,WorkExp,Knowledge_1,Knowledge_2,Knowledge_3,Knowledge_4,Knowledge_5,Knowledge_6,Knowledge_7,Frequency_1,Frequency_2,Frequency_3,TimeSearching,TimeAnswering,Onboarding,ProfessionalTech,TrueFalse_1,TrueFalse_2,TrueFalse_3,SurveyLength,SurveyEase,ConvertedCompYearly
0,1,None of these,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,I am a developer by profession,"Employed, full-time",Fully remote,Hobby;Contribute to open-source projects,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Canada,CAD\tCanadian dollar,NaN,NaN,JavaScript;TypeScript,Rust;TypeScript,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,macOS,Windows Subsystem for Linux (WSL),Git,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Very unfavorable,Collectives on Stack Overflow;Stack Overflow f...,Daily or almost daily,Yes,Daily or almost daily,Not sure,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Difficult,NaN
2,3,"I am not primarily a developer, but I write co...","Employed, full-time","Hybrid (some remote, some in-person)",Hobby,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Books / Physical media;Friend or family member...,Technical documentation;Blogs;Programming Game...,NaN,14,5,Data scientist or machine learning specialist;...,20 to 99 employees,I have some influence,NaN,United Kingdom of Great Britain and Northern I...,GBP\tPound sterling,32000.0,Yearly,C#;C++;HTML/CSS;JavaScript;Python,C#;C++;HTML/CSS;JavaScript;TypeScript,Microsoft SQL Server,Microsoft SQL Server,NaN,NaN,Angular.js,Angular;Angular.js,Pandas,.NET,NaN,NaN,Notepad++;Visual Studio,Notepad++;Visual Studio,Windows,Windows,Git,Code editor,NaN,NaN,NaN,NaN,Microsoft Teams,Microsoft Teams,Very unfavorable,Collectives on Stack Overflow;Stack Overflow;S...,Multiple times per day,Yes,Multiple times per day,Neutral,25-34 years old,Man,No,Bisexual,White,None of the above,"I have a mood or emotional disorder (e.g., dep...",No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Neither easy nor difficult,40205.0
3,4,I am a developer by profession,"Employed, full-time",Fully remote,I don’t code outside of work,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Books / Physical media;School (i.e., Universit...",NaN,NaN,20,17,"Developer, full-stack",100 to 499 employees,I have some influence,Other (please specify):,Israel,ILS\tIsraeli new shekel,60000.0,Monthly,C#;JavaScript;SQL;TypeScript,C#;SQL;TypeScript,Microsoft SQL Server,Microsoft SQL Server,NaN,NaN,ASP.NET;ASP.NET Core,ASP.NET;ASP.NET Core,.NET,.NET,NaN,NaN,Notepad++;Visual Studio;Visual Studio Code,Notepad++;Visual Studio;Visual Studio Code,Windows,Windows,Git,Code editor;Command-line;Version control hosti...,NaN,NaN,Jira Work Management;Trello,Jira Work Management;Trello,Slack;Zoom,Slack;Zoom,Very unfavorable,Collectives on Stack Overflow;Stack Overflow f...,Daily or almost daily,Yes,A few times per week,"Yes, definitely",35-44 years old,Man,No,Straight / Heterosexual,White,None of the above,None of the above,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,215232.0
4,5,I am a developer by profession,"Employed, full-time","Hybrid (some remote, some in-person)",Hobby,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Other online resources (e.g., videos, blogs, f...",Technical documentation;Blogs;Stack Overflow;O...,NaN,8,3,"Developer, front-end;Developer, full-stack;Dev...",20 to 99 employees,I have some influence,Start a free trial;Visit developer communities...,United States of America,USD\tUnited States dollar,NaN,NaN,C#;HTML/CSS;JavaScript;SQL;Swift;TypeScript,C#;Elixir;F#;Go;JavaScript;Rust;TypeScript,Cloud Firestore;Elasticsearch;Microsoft SQL Se...,Cloud Firestore;Elasticsearch;Firebase Realtim...,Firebase;Microsoft Azure,Firebase;Microsoft Azure,Angular;ASP.NET;ASP.NET Core ;jQuery;Node.js,Angular;ASP.NET Core ;Blazor;Node.js,.NET,.NET;Apache Kafka,npm,Docker;Kubernetes,Notepad++;Visual Studio;Visual Studio Code;Xcode,Rider;Visual Studio;Visual Studio Code,Windows,macOS;Windows,Git;Other (please specify):,Code editor,NaN,NaN,NaN,NaN,Microsoft Teams;Zoom,NaN,Unfavorable,Collectives on Stack Overflow;Stack Overflow f...,Multiple times per day,Yes,Daily or almost daily,"Yes, definitely",25-34 years old,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Easy,NaN

#### I just want to grab some specific columns from the original dataset. Instead of dropping tons of columns, I prefer to create a new df to work with. So, let's clean the data

In [151]:
interest_columns = ['ResponseId','MainBranch','Employment','RemoteWork','EdLevel','YearsCode','DevType','PurchaseInfluence','LanguageHaveWorkedWith','DatabaseHaveWorkedWith','PlatformHaveWorkedWith','OpSysProfessional use','OpSysPersonal use','Age','Gender','Ethnicity','WorkExp','ConvertedCompYearly']
len(interest_columns)

18

In [152]:
df = original_df[interest_columns].copy()
df.head()

,ResponseId,MainBranch,Employment,RemoteWork,EdLevel,YearsCode,DevType,PurchaseInfluence,LanguageHaveWorkedWith,DatabaseHaveWorkedWith,PlatformHaveWorkedWith,OpSysProfessional use,OpSysPersonal use,Age,Gender,Ethnicity,WorkExp,ConvertedCompYearly
0,1,None of these,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,I am a developer by profession,"Employed, full-time",Fully remote,NaN,NaN,NaN,NaN,JavaScript;TypeScript,NaN,NaN,macOS,Windows Subsystem for Linux (WSL),NaN,NaN,NaN,NaN,NaN
2,3,"I am not primarily a developer, but I write co...","Employed, full-time","Hybrid (some remote, some in-person)","Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",14,Data scientist or machine learning specialist;...,I have some influence,C#;C++;HTML/CSS;JavaScript;Python,Microsoft SQL Server,NaN,Windows,Windows,25-34 years old,Man,White,NaN,40205.0
3,4,I am a developer by profession,"Employed, full-time",Fully remote,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",20,"Developer, full-stack",I have some influence,C#;JavaScript;SQL;TypeScript,Microsoft SQL Server,NaN,Windows,Windows,35-44 years old,Man,White,NaN,215232.0
4,5,I am a developer by profession,"Employed, full-time","Hybrid (some remote, some in-person)","Bachelor’s degree (B.A., B.S., B.Eng., etc.)",8,"Developer, front-end;Developer, full-stack;Dev...",I have some influence,C#;HTML/CSS;JavaScript;SQL;Swift;TypeScript,Cloud Firestore;Elasticsearch;Microsoft SQL Se...,Firebase;Microsoft Azure,Windows,macOS;Windows,25-34 years old,NaN,NaN,NaN,NaN

In [153]:
df.set_index('ResponseId', inplace=True)

In [154]:
df.rename(columns={
    'ConvertedCompYearly':'YearlySalary','DatabaseHaveWorkedWith':'WorkedDatabase',\
    'DevType':'CurrentJob','LanguageHaveWorkedWith':'WorkedLanguage',\
    'PlatformHaveWorkedWith':'WorkedPlatform','PurchaseInfluence':'Influence'},inplace=True)

In [155]:
df.sort_index(axis='columns',inplace=True)

In [156]:
df.head()

,Age,CurrentJob,EdLevel,Employment,Ethnicity,Gender,Influence,MainBranch,OpSysPersonal use,OpSysProfessional use,RemoteWork,WorkExp,WorkedDatabase,WorkedLanguage,WorkedPlatform,YearlySalary,YearsCode
ResponseId,,,,,,,,,,,,,,,,,
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None of these,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,"Employed, full-time",NaN,NaN,NaN,I am a developer by profession,Windows Subsystem for Linux (WSL),macOS,Fully remote,NaN,NaN,JavaScript;TypeScript,NaN,NaN,NaN
3,25-34 years old,Data scientist or machine learning specialist;...,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","Employed, full-time",White,Man,I have some influence,"I am not primarily a developer, but I write co...",Windows,Windows,"Hybrid (some remote, some in-person)",NaN,Microsoft SQL Server,C#;C++;HTML/CSS;JavaScript;Python,NaN,40205.0,14
4,35-44 years old,"Developer, full-stack","Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Employed, full-time",White,Man,I have some influence,I am a developer by profession,Windows,Windows,Fully remote,NaN,Microsoft SQL Server,C#;JavaScript;SQL;TypeScript,NaN,215232.0,20
5,25-34 years old,"Developer, front-end;Developer, full-stack;Dev...","Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Employed, full-time",NaN,NaN,I have some influence,I am a developer by profession,macOS;Windows,Windows,"Hybrid (some remote, some in-person)",NaN,Cloud Firestore;Elasticsearch;Microsoft SQL Se...,C#;HTML/CSS;JavaScript;SQL;Swift;TypeScript,Firebase;Microsoft Azure,NaN,8

Perfect. Now that I've the interesting features that I want for my purpose, let's find some insights.

In [157]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 73268 entries, 1 to 73268
Data columns (total 17 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Age                    70946 non-null  object
 1   CurrentJob             61302 non-null  object
 2   EdLevel                71571 non-null  object
 3   Employment             71709 non-null  object
 4   Ethnicity              69474 non-null  object
 5   Gender                 70853 non-null  object
 6   Influence              50969 non-null  object
 7   MainBranch             73268 non-null  object
 8   OpSysPersonal use      70963 non-null  object
 9   OpSysProfessional use  65503 non-null  object
 10  RemoteWork             58958 non-null  object
 11  WorkExp                36769 non-null  float64
 12  WorkedDatabase         60121 non-null  object
 13  WorkedLanguage         70975 non-null  object
 14  WorkedPlatform         49924 non-null  object
 15  YearlySalary           38071 non-null  float64
 16  YearsCode              71331 non-null  object
dtypes: float64(2), object(15)
memory usage: 10.1+ MB

In [158]:
# Why does 'YearsCode' is an object?
df['YearsCode'].unique()

array([nan, '14', '20', '8', '15', '3', '1', '6', '37', '5', '12', '22',
       '11', '4', '7', '13', '36', '2', '25', '10', '40', '16', '27',
       '24', '19', '9', '17', '18', '26', 'More than 50 years', '29',
       '30', '32', 'Less than 1 year', '48', '45', '38', '39', '28', '23',
       '43', '21', '41', '35', '50', '33', '31', '34', '46', '44', '42',
       '47', '49'], dtype=object)

In [159]:
df['YearsCode'].replace('Less than 1 year',0,inplace=True)
df['YearsCode'].replace('More than 50 years',55,inplace=True)

In [160]:
df['YearsCode'] = df['YearsCode'].astype(float)

In [161]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 73268 entries, 1 to 73268
Data columns (total 17 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Age                    70946 non-null  object
 1   CurrentJob             61302 non-null  object
 2   EdLevel                71571 non-null  object
 3   Employment             71709 non-null  object
 4   Ethnicity              69474 non-null  object
 5   Gender                 70853 non-null  object
 6   Influence              50969 non-null  object
 7   MainBranch             73268 non-null  object
 8   OpSysPersonal use      70963 non-null  object
 9   OpSysProfessional use  65503 non-null  object
 10  RemoteWork             58958 non-null  object
 11  WorkExp                36769 non-null  float64
 12  WorkedDatabase         60121 non-null  object
 13  WorkedLanguage         70975 non-null  object
 14  WorkedPlatform         49924 non-null  object
 15  YearlySalary           38071 non-null  float64
 16  YearsCode              71331 non-null  float64
dtypes: float64(3), object(14)
memory usage: 10.1+ MB

In [162]:
df.describe()

            WorkExp  YearlySalary     YearsCode
count  36769.000000  3.807100e+04  71331.000000
mean      10.242378  1.707613e+05     12.260952
std        8.706850  7.814132e+05      9.991828
min        0.000000  1.000000e+00      0.000000
25%        4.000000  3.583200e+04      5.000000
50%        8.000000  6.784500e+04      9.000000
75%       15.000000  1.200000e+05     16.000000
max       50.000000  5.000000e+07     55.000000

I think that this new dataset is perfect to practice with :D. I will be practicing with this survey along my learning, so I think this is just going to be the first part of a series of practicing proyects.

In [163]:
df.to_csv('/Users/daniboy/Desktop/Youtube_Courses/Pandas_Corey_Schafer/Pandas_project/Interest_SO_survey_insights.csv')